classdef dynamic_optimization < yop.relation
    
    methods (Static)
        
        function bool = dynamics(constraint)
            % Does the constraint describe the system dynamics
            bool = isequal(constraint.operation, @eq) && ...
                (...
                isequal(constraint.left.operation, @yop.der) || ...
                isequal(constraint.right.operation, @yop.der) || ...
                isequal(constraint.left.operation, @yop.alg) || ...
                isequal(constraint.right.operation, @yop.alg) ...
                );
        end
        
    end
    
end