%% Nondifferentiable system
% Author: Dennis Edblom
sys = YopSystem(...
    'states', 3, ...
    'controls', 1, ...
    'model', @nonDiffModel);
% Symbolic variables
t = sys.t;
x = sys.x;
u = sys.u;

% Phase description
ocp = YopOcp();
ocp.min({ t_f( x(3) ) });
ocp.st(...
     'systems', sys, ...
     ... % Initial conditions
    { 0 '==' t_0(x(1)) }, ...
    { 0 '==' t_0(x(2)) }, ...
    { 0 '==' t_0(x(3)) }, ...
    ... % Final conditions
    { 2 '==' t_f( t )  } ...
    );

w0 = YopInitialGuess(...
    'signals', [t; x; u], ...
    'signalValues', [0; 0; 0; 0; -5] ...
    );

sol = ocp.solve(...
    'controlIntervals', 100, ...
    'collocationPoints', 'radau', ...
    'polynomialDegree', 3, ...
    'initialGuess', w0);

%% Plot the results
figure(1)
subplot(2,1,1)
sol.plot(t,x);
legend('x1','x2','x3');
title('Nondiff System state variable');

subplot(2,1,2)
sol.plot(t,u);
legend('u');
title('Nondiff System control');